# Generated by Django 2.2.3 on 2019-10-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecoes_2018', '0002_auto_20191012_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecao',
            options={},
        ),
        migrations.AlterModelTable(
            name='projecao',
            table=None,
        ),
    ]
