# Generated by Django 2.2.3 on 2019-10-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecoes_2018', '0003_auto_20191012_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecao',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='projecao',
            table='projecao',
        ),
    ]
